# Generated by Django 4.1.3 on 2022-11-14 17:51

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_profile_bio_profile_created_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default-user.png', null=True, upload_to=userauths.models.user_director_path, verbose_name='Picture'),
        ),
    ]
